Updated fanspeed script

diff --git a/fanspeed b/fanspeed
--- a/fanspeed
+++ b/fanspeed
@@ -1,8 +1,21 @@
 #!/usr/bin/env sh
+
+command -v figlet >/dev/null 2>&1 || { echo >&2 "Figlet is missing. Run sudo apt install figlet to continue....."; exit 1; }
+
 clear
 figlet -c Applesmc fan controller
+
+APPLESMC="/sys/module/applesmc/drivers/platform:applesmc/applesmc.768/"
+if [ -d "$APPLESMC" ]; then
+
 echo "\nTested on mid 2013 apple macbook pro, might work on some later macbooks.\n"
 echo -n "Enter fan speed 1 - 8000: " ; read x
 echo $x > /sys/module/applesmc/drivers/platform:applesmc/applesmc.768/fan1_min
 clear
+
+else
+
+echo "Error: ${DIR} not found. Can not continue."
+read -n 1 -s
+fi
 
